name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      TOKEN: ${{ secrets.TOKEN }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --build-arg CLIENT_ID=$CLIENT_ID --build-arg TOKEN=$TOKEN . --file Dockerfile --tag cs-club-bot:$(date +%s)
